apiVersion: v1
kind: Service
metadata:
  name: onmyway-auth
spec:
  selector:
    app: onmyway
    tier: auth
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onmyway-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onmyway
      tier: auth
  template:
    metadata:
      labels:
        app: onmyway
        tier: auth
    spec:
      containers: # TODO: Set the resource limits for the container
        - name: onmyway-auth
          image: seyunjang/omw_auth_v3:latest
          env:
            - name: PROXY_ADDRESS
              value: "onmyway-api.default"
