---
apiVersion: v1
kind: Service
metadata:
  name: onmyway-api
spec:
  selector:
    app: onmyway
    tier: api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 80
  externalIPs:
    - 34.64.122.206
    - 34.47.65.56
  type: NodePort #FIXME: Change this to LoadBalancer (applly Ingress Controller in advance)

---
apiVersion: v1
kind: Service
metadata:
  name: onmyway-auth
spec:
  selector:
    app: onmyway
    tier: auth
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  externalIPs:
    - 34.64.122.206
    - 34.47.65.56
  type: NodePort #FIXME: Change this to LoadBalancer (applly Ingress Controller in advance)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onmyway-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onmyway
      tier: api
  template:
    metadata:
      labels:
        app: onmyway
        tier: api
    spec:
      containers: # TODO: Set the resource limits for the container
        - name: onmyway-api
          image: seyunjang/omw_api_v3:latest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onmyway-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onmyway
      tier: auth
  template:
    metadata:
      labels:
        app: onmyway
        tier: auth
    spec:
      containers: # TODO: Set the resource limits for the container
        - name: onmyway-auth
          image: seyunjang/omw_auth_v3:latest
          env:
            - name: PROXY_ADDRESS
              value: "onmyway-api.default"
