spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: proxy_route
            uri: http://localhost:80
            predicates:
              - Path=/map/**
  config:
    activate:
      on-profile: local

  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbbonmyway"

  datasource:
    url: "jdbc:mysql://localhost:3306/onmyway"
    username: "root"
    password: "jjgg0825"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
---
spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gateway:
      mvc:
        routes:
          - id: proxy_routes
            uri: http://${ONMYWAY_API_SERVICE_HOST}:8080
            predicates:
              - Path=/map/**

  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbbonmyway"

  datasource:
    url: "jdbc:mysql://onmyway.c32400yosduj.ap-northeast-2.rds.amazonaws.com:3306/onmyway"
    username: "admin"
    password: "onmyway_123" #FIXME: fix this security issue
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
