spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: proxy_route
            uri: http://localhost:80
            predicates:
              - Path=/map/**
  config:
    activate:
      on-profile: local

  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbbonmyway"

  datasource:
    url: "jdbc:mysql://localhost:3306/onmyway"
    username: "root"
    password: "1052"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gateway:
      mvc:
        routes:
          - id: proxy_routes
            uri: http://alb-omw-986932733.ap-northeast-2.elb.amazonaws.com
            predicates:
              - Path=/map/**

  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbbonmyway"

  datasource:
    #    url: "jdbc:mysql://onmyway-db-test.cnuan9yf9psv.ap-northeast-2.rds.amazonaws.com:3306/onmyway" #TODO: update to AWS RDS
    url: "jdbc:mysql://onmyway-db-prod.cnuan9yf9psv.ap-northeast-2.rds.amazonaws.com:3306/onmyway" #TODO: update to AWS RDS
    username: "root"
    password: "admin_lgcns" #FIXME: security issue
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect