apiVersion: v1
kind: Service
metadata:
  name: onmyway-api
spec:
  selector:
    app: onmyway
    tier: api
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onmyway-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onmyway
      tier: api
  template:
    metadata:
      labels:
        app: onmyway
        tier: api
    spec:
      containers: # TODO: Set the resource limits for the container
        - name: onmyway-be
          image: seyunjang/omw_api_v3:latest
